function [rho,d,shortstr,longstr,legendstr] = ModelInfo(modelname)

filename = mfilename('fullpath');
path = fileparts(filename);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
modelsQ     = {'Q1','Q2','Q3'};
modelnamesQ = {'Quebec Model 1','Quebec Model 2','Quebec Model 3'};

for i = 1:length(modelnamesQ)
    legendstringsQ{i} = ['USGS ',modelsQ{i}];
    filenamesQ{i} = sprintf('%s/../QuebecModels/%s.txt',path,modelsQ{i});
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
modelsU = {'AK1','AK2','AP1','AP2','BR1','CL1','CO1',...
	   'CP1','CP2','CS1','IP1','IP2',...
	  'IP3','IP4','NE1','PB1','PB2','PT1','SL1','SU1'};

modelnamesU = {...
    'Adirondack Mountains',...
    'Appalachan Plateaus',...
    'Northern Appalachan Plateaus',...
    'Northwest Basin and Range',...
    'Colorado Plateau',...
    'Columbia Plateau',...
    'Coastal Plain (South Carolina)',...
    'Coastal Plain (Georgia)',...
    'Cascade-Sierra Mountains',...
    'Florida Peninsula',...
    'Interior Plains (North Dakota)',...
    'Interior Plains',...
    'Interior Plains (Michigan)',...
    'Interior Plains (Great Plains)',...
    'New England',...
    'Pacific Border (Willamette Valley)',...
    'Pacific Border (Puget Lowlands)',...
    'Piedmont',...
    'St. Lawrence Lowlands',...
    'Superior Upland'...
};

for i = 1:length(modelnamesU)
    legendstringsU{i} = ['USGS ',modelsU{i}];
    filenamesU{i} = sprintf('%s/../USGSModels/%s_GroundModel.txt',...
			    path,modelsU{i});
end

models        = {modelsQ{:},modelsU{:}};
modelnames    = {modelnamesQ{:},modelnamesU{:}};
legendstrings = {legendstringsQ{:},legendstringsU{:}};
filenames     = {filenamesQ{:},filenamesU{:}};

if (nargin == 0)
    rho = models;
    return
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for m = 1:length(models)
    if strcmp(models{m},modelname)
	break;
    end
end
shortstr  = models{m};
longstr   = modelnames{m};
legendstr = legendstrings{m};
rho_h = load(filenames{m});
rho = rho_h(:,1);
d   = rho_h(:,2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

